name: Deploy app to server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  whitelist_ip:
    runs-on: ubuntu-latest
    steps:
    - name: Get runner IP
      run: |
        ip=`curl https://ipinfo.io/ip`
        echo $ip
        echo "action_runner_ip=$ip" >> $GITHUB_ENV
    - name: Add Github Actions IP to Security group as a inbound rule
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_STAGING_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.action_runner_ip }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        
## Run other procedure here

    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_STAGING_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.action_runner_ip }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      if: always()
